---
root: true

plugins:
  - jest
  # - babel

env:
  node: true
  jest: true
  browser: true
  es2021: true

# parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  eqeqeq: 0